// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-v2-vibes/Atelier.tsx": () => import("../components/mockups/home-v2-vibes/Atelier.tsx"),
  "./components/mockups/home-v2-vibes/Signal.tsx": () => import("../components/mockups/home-v2-vibes/Signal.tsx"),
  "./components/mockups/home-v2-vibes/Tribunal.tsx": () => import("../components/mockups/home-v2-vibes/Tribunal.tsx"),
  "./components/mockups/home-inversions/Dense.tsx": () => import("../components/mockups/home-inversions/Dense.tsx"),
  "./components/mockups/home-inversions/Still.tsx": () => import("../components/mockups/home-inversions/Still.tsx")
};
